
 language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_waiter_test
  

node_js:  
  - 12

before_script:
  - psql -c 'create database my_waiter_test;' -U postgres
  - psql -U postgres -d my_waiter_test -a -f tables.sql

services:
  - postgresql